// Phase B 사전 마이그레이션 스크립트
// ------------------------------------------------------------
// 용도: 기존 public."Users" 4명을 auth.users로 생성하고,
//       _migration_user_id_map 테이블 (bigint old_id → uuid new_uuid)
//       을 채울 SQL을 stdout으로 출력.
//
// 사용법:
//   SUPABASE_URL='https://gaibakqhdfdpnsdgpmya.supabase.co' \
//   SUPABASE_SERVICE_ROLE_KEY='<service_role_key>' \
//   node supabase/scripts/phase_b_pre_migrate.mjs > phase_b_map.sql
//
// 그 다음:
//   1. phase_b_map.sql 내용을 Supabase 대시보드 SQL Editor에 붙여넣고 RUN
//   2. supabase db push  (메인 마이그레이션 자동 적용)
//
// 주의: SERVICE_ROLE 키는 절대 클라이언트/git에 노출 금지.
// ------------------------------------------------------------

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const URL = process.env.SUPABASE_URL
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!URL || !KEY) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars required.')
  process.exit(1)
}

const supabase = createClient(URL, KEY, {
  auth: { autoRefreshToken: false, persistSession: false }
})

// 1) 기존 Users 조회
const { data: users, error: fetchErr } = await supabase
  .from('Users')
  .select('id, name, phone, kakao_id, plan')
  .order('id', { ascending: true })

if (fetchErr) {
  console.error('Failed to fetch Users:', fetchErr)
  process.exit(1)
}

console.error(`Found ${users.length} existing Users — migrating to auth.users...`)

const mapping = []

for (const u of users) {
  // 카카오 ID 우선, 없으면 전화번호로 placeholder 이메일 생성
  const phoneDigits = (u.phone || '').replace(/[^0-9]/g, '')
  const email = u.kakao_id
    ? `kakao_${u.kakao_id}@placeholder.aidonghang.local`
    : `phone_${phoneDigits}@placeholder.aidonghang.local`

  const { data: created, error: createErr } = await supabase.auth.admin.createUser({
    email,
    email_confirm: true,
    user_metadata: {
      name: u.name,
      phone: u.phone,
      kakao_id: u.kakao_id,
      provider_id: u.kakao_id,
      migrated_from_users_id: u.id,
      migrated_at: new Date().toISOString()
    }
  })

  if (createErr) {
    console.error(`  [FAIL] Users.id=${u.id} (${u.name}): ${createErr.message}`)
    continue
  }

  mapping.push({ old_id: u.id, new_uuid: created.user.id, name: u.name })
  console.error(`  [OK]   Users.id=${u.id} (${u.name}) → ${created.user.id}`)
}

if (mapping.length !== users.length) {
  console.error(`\nERROR: only ${mapping.length}/${users.length} users migrated. Aborting SQL generation.`)
  process.exit(1)
}

// 2) SQL 출력
console.log(`-- Generated by phase_b_pre_migrate.mjs at ${new Date().toISOString()}`)
console.log(`-- Paste into Supabase SQL Editor and execute BEFORE running 'supabase db push'.`)
console.log()
console.log(`BEGIN;`)
console.log(`CREATE TABLE IF NOT EXISTS public._migration_user_id_map (`)
console.log(`  old_id   bigint PRIMARY KEY,`)
console.log(`  new_uuid uuid   NOT NULL UNIQUE`)
console.log(`);`)
console.log()
for (const m of mapping) {
  console.log(`INSERT INTO public._migration_user_id_map (old_id, new_uuid) VALUES (${m.old_id}, '${m.new_uuid}')  -- ${m.name}`)
  console.log(`  ON CONFLICT (old_id) DO UPDATE SET new_uuid = EXCLUDED.new_uuid;`)
}
console.log(`COMMIT;`)
